language: node_js
node_js:
- '0.10'
before_install:
- npm install -g npm@next
- npm install -g grunt-cli
install: npm install
before_deploy:
- grunt build
- grunt zip
- grunt codedeploy
deploy:
- provider: s3
  access_key_id: AKIAIMTOX4BXGVFOB56Q
  secret_access_key:
    secure: e3Y2WLatCBW6M++RUuGRP3y7mM5FGoSAX68ZMwfXx3L6to252ClsBNTh05f2rW3IZl1/LZUtr4WTSifPDaxWU64MoVNorUQ8DIUeQYl+OOjcDy87CFyEGEk5EDSYeQn+wphUYlGXBl6e0FsXb7FXJtBgt4XLKTNoVC9f60EyNaM=
  skip_cleanup: true
  bucket: hmda-pilot
  local_dir: dist
  upload-dir: develop
  on:
    all_branches: true
- provider: codedeploy
  access_key_id: AKIAIMTOX4BXGVFOB56Q
  secret_access_key:
    secure: e3Y2WLatCBW6M++RUuGRP3y7mM5FGoSAX68ZMwfXx3L6to252ClsBNTh05f2rW3IZl1/LZUtr4WTSifPDaxWU64MoVNorUQ8DIUeQYl+OOjcDy87CFyEGEk5EDSYeQn+wphUYlGXBl6e0FsXb7FXJtBgt4XLKTNoVC9f60EyNaM=
  bucket: hmda-pilot
  key: develop/hmda-pilot-codedeploy.zip
  application: hmda-pilot
  deployment_group: hmda-pilot-dev
  on:
    all_branches: true
- provider: s3
  access_key_id: AKIAIMTOX4BXGVFOB56Q
  secret_access_key:
    secure: e3Y2WLatCBW6M++RUuGRP3y7mM5FGoSAX68ZMwfXx3L6to252ClsBNTh05f2rW3IZl1/LZUtr4WTSifPDaxWU64MoVNorUQ8DIUeQYl+OOjcDy87CFyEGEk5EDSYeQn+wphUYlGXBl6e0FsXb7FXJtBgt4XLKTNoVC9f60EyNaM=
  skip_cleanup: true
  bucket: hmda-pilot
  local_dir: dist
  upload-dir: master
  on:
    branch: master
- provider: codedeploy
  access_key_id: AKIAIMTOX4BXGVFOB56Q
  secret_access_key:
    secure: e3Y2WLatCBW6M++RUuGRP3y7mM5FGoSAX68ZMwfXx3L6to252ClsBNTh05f2rW3IZl1/LZUtr4WTSifPDaxWU64MoVNorUQ8DIUeQYl+OOjcDy87CFyEGEk5EDSYeQn+wphUYlGXBl6e0FsXb7FXJtBgt4XLKTNoVC9f60EyNaM=
  bucket: hmda-pilot
  key: master/hmda-pilot-codedeploy.zip
  application: hmda-pilot
  deployment_group: hmda-pilot-prod
  on:
    branch: master
