language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g npm@next
  - npm install -g grunt-cli
install: npm install
before_deploy:
  - grunt build
  - grunt zip
  - grunt codedeploy
deploy:
  - provider: s3
    access_key_id: AKIAIMTOX4BXGVFOB56Q
    secret_access_key:
      secure: NxMG05K8yLXd8XH4U+u2B5kF4Tr0HoIox3qUKWi4BqLK5Ze2dMaCHQZCBz2hCrdPY+Jj5AiktyTF9PeRn2gz/jOsT5XVh/I1XG7xk7s6w6ml13vdwNbp2ZVo0ENXjmQ1OT44a8QebhbqJwjiaQ2sERGNRM6nqbKpwOFdbL50VoQ=
    skip_cleanup: true
    bucket: hmda-pilot
    local_dir: dist
    upload-dir: develop
    on:
      all_branches: true
  - provider: codedeploy
    access_key_id: AKIAIMTOX4BXGVFOB56Q
    secret_access_key:
      secure: NxMG05K8yLXd8XH4U+u2B5kF4Tr0HoIox3qUKWi4BqLK5Ze2dMaCHQZCBz2hCrdPY+Jj5AiktyTF9PeRn2gz/jOsT5XVh/I1XG7xk7s6w6ml13vdwNbp2ZVo0ENXjmQ1OT44a8QebhbqJwjiaQ2sERGNRM6nqbKpwOFdbL50VoQ=
    bucket: hmda-pilot
    key: develop/hmda-pilot-codedeploy.zip
    application: hmda-pilot
    deployment_group: hmda-pilot-dev
    on:
      all_branches: true
  - provider: s3
    access_key_id: AKIAIMTOX4BXGVFOB56Q
    secret_access_key:
      secure: NxMG05K8yLXd8XH4U+u2B5kF4Tr0HoIox3qUKWi4BqLK5Ze2dMaCHQZCBz2hCrdPY+Jj5AiktyTF9PeRn2gz/jOsT5XVh/I1XG7xk7s6w6ml13vdwNbp2ZVo0ENXjmQ1OT44a8QebhbqJwjiaQ2sERGNRM6nqbKpwOFdbL50VoQ=
    skip_cleanup: true
    bucket: hmda-pilot
    local_dir: dist
    upload-dir: master
    on:
      branch: master
  - provider: codedeploy
    access_key_id: AKIAIMTOX4BXGVFOB56Q
    secret_access_key:
      secure: NxMG05K8yLXd8XH4U+u2B5kF4Tr0HoIox3qUKWi4BqLK5Ze2dMaCHQZCBz2hCrdPY+Jj5AiktyTF9PeRn2gz/jOsT5XVh/I1XG7xk7s6w6ml13vdwNbp2ZVo0ENXjmQ1OT44a8QebhbqJwjiaQ2sERGNRM6nqbKpwOFdbL50VoQ=
    bucket: hmda-pilot
    key: master/hmda-pilot-codedeploy.zip
    application: hmda-pilot
    deployment_group: hmda-pilot-prod
    on:
      branch: master
